/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mteo.savand.avro_generate.batch;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class WeatherObject extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8916708864821696705L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"WeatherObject\",\"namespace\":\"mteo.savand.avro_generate.batch\",\"fields\":[{\"name\":\"stationId\",\"type\":\"int\"},{\"name\":\"geoLocationObject\",\"type\":{\"type\":\"record\",\"name\":\"GeoLocationObject\",\"fields\":[{\"name\":\"latitude\",\"type\":\"float\"},{\"name\":\"longitude\",\"type\":\"float\"}]}},{\"name\":\"date\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"temperatureInDegreesCelsious\",\"type\":\"int\"},{\"name\":\"humidityInPercentage\",\"type\":\"int\"},{\"name\":\"wind\",\"type\":{\"type\":\"record\",\"name\":\"WindObject\",\"fields\":[{\"name\":\"windSpeedInKnots\",\"type\":\"int\"},{\"name\":\"direction\",\"type\":{\"type\":\"enum\",\"name\":\"WindDirection\",\"symbols\":[\"N\",\"NNE\",\"NE\",\"ENE\",\"E\",\"ESE\",\"SE\",\"SSE\",\"S\",\"SSW\",\"SW\",\"WSW\",\"W\",\"WNW\",\"NW\",\"NNW\"]}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int stationId;
  @Deprecated public mteo.savand.avro_generate.batch.GeoLocationObject geoLocationObject;
  @Deprecated public org.joda.time.DateTime date;
  @Deprecated public int temperatureInDegreesCelsious;
  @Deprecated public int humidityInPercentage;
  @Deprecated public mteo.savand.avro_generate.batch.WindObject wind;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public WeatherObject() {}

  /**
   * All-args constructor.
   * @param stationId The new value for stationId
   * @param geoLocationObject The new value for geoLocationObject
   * @param date The new value for date
   * @param temperatureInDegreesCelsious The new value for temperatureInDegreesCelsious
   * @param humidityInPercentage The new value for humidityInPercentage
   * @param wind The new value for wind
   */
  public WeatherObject(java.lang.Integer stationId, mteo.savand.avro_generate.batch.GeoLocationObject geoLocationObject, org.joda.time.DateTime date, java.lang.Integer temperatureInDegreesCelsious, java.lang.Integer humidityInPercentage, mteo.savand.avro_generate.batch.WindObject wind) {
    this.stationId = stationId;
    this.geoLocationObject = geoLocationObject;
    this.date = date;
    this.temperatureInDegreesCelsious = temperatureInDegreesCelsious;
    this.humidityInPercentage = humidityInPercentage;
    this.wind = wind;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return stationId;
    case 1: return geoLocationObject;
    case 2: return date;
    case 3: return temperatureInDegreesCelsious;
    case 4: return humidityInPercentage;
    case 5: return wind;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  protected static final org.apache.avro.data.TimeConversions.DateConversion DATE_CONVERSION = new org.apache.avro.data.TimeConversions.DateConversion();
  protected static final org.apache.avro.data.TimeConversions.TimeConversion TIME_CONVERSION = new org.apache.avro.data.TimeConversions.TimeConversion();
  protected static final org.apache.avro.data.TimeConversions.TimestampConversion TIMESTAMP_CONVERSION = new org.apache.avro.data.TimeConversions.TimestampConversion();

  private final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      TIMESTAMP_CONVERSION,
      null,
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: stationId = (java.lang.Integer)value$; break;
    case 1: geoLocationObject = (mteo.savand.avro_generate.batch.GeoLocationObject)value$; break;
    case 2: date = (org.joda.time.DateTime)value$; break;
    case 3: temperatureInDegreesCelsious = (java.lang.Integer)value$; break;
    case 4: humidityInPercentage = (java.lang.Integer)value$; break;
    case 5: wind = (mteo.savand.avro_generate.batch.WindObject)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'stationId' field.
   * @return The value of the 'stationId' field.
   */
  public java.lang.Integer getStationId() {
    return stationId;
  }

  /**
   * Sets the value of the 'stationId' field.
   * @param value the value to set.
   */
  public void setStationId(java.lang.Integer value) {
    this.stationId = value;
  }

  /**
   * Gets the value of the 'geoLocationObject' field.
   * @return The value of the 'geoLocationObject' field.
   */
  public mteo.savand.avro_generate.batch.GeoLocationObject getGeoLocationObject() {
    return geoLocationObject;
  }

  /**
   * Sets the value of the 'geoLocationObject' field.
   * @param value the value to set.
   */
  public void setGeoLocationObject(mteo.savand.avro_generate.batch.GeoLocationObject value) {
    this.geoLocationObject = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public org.joda.time.DateTime getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(org.joda.time.DateTime value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'temperatureInDegreesCelsious' field.
   * @return The value of the 'temperatureInDegreesCelsious' field.
   */
  public java.lang.Integer getTemperatureInDegreesCelsious() {
    return temperatureInDegreesCelsious;
  }

  /**
   * Sets the value of the 'temperatureInDegreesCelsious' field.
   * @param value the value to set.
   */
  public void setTemperatureInDegreesCelsious(java.lang.Integer value) {
    this.temperatureInDegreesCelsious = value;
  }

  /**
   * Gets the value of the 'humidityInPercentage' field.
   * @return The value of the 'humidityInPercentage' field.
   */
  public java.lang.Integer getHumidityInPercentage() {
    return humidityInPercentage;
  }

  /**
   * Sets the value of the 'humidityInPercentage' field.
   * @param value the value to set.
   */
  public void setHumidityInPercentage(java.lang.Integer value) {
    this.humidityInPercentage = value;
  }

  /**
   * Gets the value of the 'wind' field.
   * @return The value of the 'wind' field.
   */
  public mteo.savand.avro_generate.batch.WindObject getWind() {
    return wind;
  }

  /**
   * Sets the value of the 'wind' field.
   * @param value the value to set.
   */
  public void setWind(mteo.savand.avro_generate.batch.WindObject value) {
    this.wind = value;
  }

  /**
   * Creates a new WeatherObject RecordBuilder.
   * @return A new WeatherObject RecordBuilder
   */
  public static mteo.savand.avro_generate.batch.WeatherObject.Builder newBuilder() {
    return new mteo.savand.avro_generate.batch.WeatherObject.Builder();
  }

  /**
   * Creates a new WeatherObject RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new WeatherObject RecordBuilder
   */
  public static mteo.savand.avro_generate.batch.WeatherObject.Builder newBuilder(mteo.savand.avro_generate.batch.WeatherObject.Builder other) {
    return new mteo.savand.avro_generate.batch.WeatherObject.Builder(other);
  }

  /**
   * Creates a new WeatherObject RecordBuilder by copying an existing WeatherObject instance.
   * @param other The existing instance to copy.
   * @return A new WeatherObject RecordBuilder
   */
  public static mteo.savand.avro_generate.batch.WeatherObject.Builder newBuilder(mteo.savand.avro_generate.batch.WeatherObject other) {
    return new mteo.savand.avro_generate.batch.WeatherObject.Builder(other);
  }

  /**
   * RecordBuilder for WeatherObject instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<WeatherObject>
    implements org.apache.avro.data.RecordBuilder<WeatherObject> {

    private int stationId;
    private mteo.savand.avro_generate.batch.GeoLocationObject geoLocationObject;
    private mteo.savand.avro_generate.batch.GeoLocationObject.Builder geoLocationObjectBuilder;
    private org.joda.time.DateTime date;
    private int temperatureInDegreesCelsious;
    private int humidityInPercentage;
    private mteo.savand.avro_generate.batch.WindObject wind;
    private mteo.savand.avro_generate.batch.WindObject.Builder windBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mteo.savand.avro_generate.batch.WeatherObject.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.stationId)) {
        this.stationId = data().deepCopy(fields()[0].schema(), other.stationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.geoLocationObject)) {
        this.geoLocationObject = data().deepCopy(fields()[1].schema(), other.geoLocationObject);
        fieldSetFlags()[1] = true;
      }
      if (other.hasGeoLocationObjectBuilder()) {
        this.geoLocationObjectBuilder = mteo.savand.avro_generate.batch.GeoLocationObject.newBuilder(other.getGeoLocationObjectBuilder());
      }
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.temperatureInDegreesCelsious)) {
        this.temperatureInDegreesCelsious = data().deepCopy(fields()[3].schema(), other.temperatureInDegreesCelsious);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.humidityInPercentage)) {
        this.humidityInPercentage = data().deepCopy(fields()[4].schema(), other.humidityInPercentage);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.wind)) {
        this.wind = data().deepCopy(fields()[5].schema(), other.wind);
        fieldSetFlags()[5] = true;
      }
      if (other.hasWindBuilder()) {
        this.windBuilder = mteo.savand.avro_generate.batch.WindObject.newBuilder(other.getWindBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing WeatherObject instance
     * @param other The existing instance to copy.
     */
    private Builder(mteo.savand.avro_generate.batch.WeatherObject other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.stationId)) {
        this.stationId = data().deepCopy(fields()[0].schema(), other.stationId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.geoLocationObject)) {
        this.geoLocationObject = data().deepCopy(fields()[1].schema(), other.geoLocationObject);
        fieldSetFlags()[1] = true;
      }
      this.geoLocationObjectBuilder = null;
      if (isValidValue(fields()[2], other.date)) {
        this.date = data().deepCopy(fields()[2].schema(), other.date);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.temperatureInDegreesCelsious)) {
        this.temperatureInDegreesCelsious = data().deepCopy(fields()[3].schema(), other.temperatureInDegreesCelsious);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.humidityInPercentage)) {
        this.humidityInPercentage = data().deepCopy(fields()[4].schema(), other.humidityInPercentage);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.wind)) {
        this.wind = data().deepCopy(fields()[5].schema(), other.wind);
        fieldSetFlags()[5] = true;
      }
      this.windBuilder = null;
    }

    /**
      * Gets the value of the 'stationId' field.
      * @return The value.
      */
    public java.lang.Integer getStationId() {
      return stationId;
    }

    /**
      * Sets the value of the 'stationId' field.
      * @param value The value of 'stationId'.
      * @return This builder.
      */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder setStationId(int value) {
      validate(fields()[0], value);
      this.stationId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'stationId' field has been set.
      * @return True if the 'stationId' field has been set, false otherwise.
      */
    public boolean hasStationId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'stationId' field.
      * @return This builder.
      */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder clearStationId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'geoLocationObject' field.
      * @return The value.
      */
    public mteo.savand.avro_generate.batch.GeoLocationObject getGeoLocationObject() {
      return geoLocationObject;
    }

    /**
      * Sets the value of the 'geoLocationObject' field.
      * @param value The value of 'geoLocationObject'.
      * @return This builder.
      */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder setGeoLocationObject(mteo.savand.avro_generate.batch.GeoLocationObject value) {
      validate(fields()[1], value);
      this.geoLocationObjectBuilder = null;
      this.geoLocationObject = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'geoLocationObject' field has been set.
      * @return True if the 'geoLocationObject' field has been set, false otherwise.
      */
    public boolean hasGeoLocationObject() {
      return fieldSetFlags()[1];
    }

    /**
     * Gets the Builder instance for the 'geoLocationObject' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public mteo.savand.avro_generate.batch.GeoLocationObject.Builder getGeoLocationObjectBuilder() {
      if (geoLocationObjectBuilder == null) {
        if (hasGeoLocationObject()) {
          setGeoLocationObjectBuilder(mteo.savand.avro_generate.batch.GeoLocationObject.newBuilder(geoLocationObject));
        } else {
          setGeoLocationObjectBuilder(mteo.savand.avro_generate.batch.GeoLocationObject.newBuilder());
        }
      }
      return geoLocationObjectBuilder;
    }

    /**
     * Sets the Builder instance for the 'geoLocationObject' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder setGeoLocationObjectBuilder(mteo.savand.avro_generate.batch.GeoLocationObject.Builder value) {
      clearGeoLocationObject();
      geoLocationObjectBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'geoLocationObject' field has an active Builder instance
     * @return True if the 'geoLocationObject' field has an active Builder instance
     */
    public boolean hasGeoLocationObjectBuilder() {
      return geoLocationObjectBuilder != null;
    }

    /**
      * Clears the value of the 'geoLocationObject' field.
      * @return This builder.
      */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder clearGeoLocationObject() {
      geoLocationObject = null;
      geoLocationObjectBuilder = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public org.joda.time.DateTime getDate() {
      return date;
    }

    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder setDate(org.joda.time.DateTime value) {
      validate(fields()[2], value);
      this.date = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder clearDate() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'temperatureInDegreesCelsious' field.
      * @return The value.
      */
    public java.lang.Integer getTemperatureInDegreesCelsious() {
      return temperatureInDegreesCelsious;
    }

    /**
      * Sets the value of the 'temperatureInDegreesCelsious' field.
      * @param value The value of 'temperatureInDegreesCelsious'.
      * @return This builder.
      */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder setTemperatureInDegreesCelsious(int value) {
      validate(fields()[3], value);
      this.temperatureInDegreesCelsious = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'temperatureInDegreesCelsious' field has been set.
      * @return True if the 'temperatureInDegreesCelsious' field has been set, false otherwise.
      */
    public boolean hasTemperatureInDegreesCelsious() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'temperatureInDegreesCelsious' field.
      * @return This builder.
      */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder clearTemperatureInDegreesCelsious() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'humidityInPercentage' field.
      * @return The value.
      */
    public java.lang.Integer getHumidityInPercentage() {
      return humidityInPercentage;
    }

    /**
      * Sets the value of the 'humidityInPercentage' field.
      * @param value The value of 'humidityInPercentage'.
      * @return This builder.
      */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder setHumidityInPercentage(int value) {
      validate(fields()[4], value);
      this.humidityInPercentage = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'humidityInPercentage' field has been set.
      * @return True if the 'humidityInPercentage' field has been set, false otherwise.
      */
    public boolean hasHumidityInPercentage() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'humidityInPercentage' field.
      * @return This builder.
      */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder clearHumidityInPercentage() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'wind' field.
      * @return The value.
      */
    public mteo.savand.avro_generate.batch.WindObject getWind() {
      return wind;
    }

    /**
      * Sets the value of the 'wind' field.
      * @param value The value of 'wind'.
      * @return This builder.
      */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder setWind(mteo.savand.avro_generate.batch.WindObject value) {
      validate(fields()[5], value);
      this.windBuilder = null;
      this.wind = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'wind' field has been set.
      * @return True if the 'wind' field has been set, false otherwise.
      */
    public boolean hasWind() {
      return fieldSetFlags()[5];
    }

    /**
     * Gets the Builder instance for the 'wind' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public mteo.savand.avro_generate.batch.WindObject.Builder getWindBuilder() {
      if (windBuilder == null) {
        if (hasWind()) {
          setWindBuilder(mteo.savand.avro_generate.batch.WindObject.newBuilder(wind));
        } else {
          setWindBuilder(mteo.savand.avro_generate.batch.WindObject.newBuilder());
        }
      }
      return windBuilder;
    }

    /**
     * Sets the Builder instance for the 'wind' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder setWindBuilder(mteo.savand.avro_generate.batch.WindObject.Builder value) {
      clearWind();
      windBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'wind' field has an active Builder instance
     * @return True if the 'wind' field has an active Builder instance
     */
    public boolean hasWindBuilder() {
      return windBuilder != null;
    }

    /**
      * Clears the value of the 'wind' field.
      * @return This builder.
      */
    public mteo.savand.avro_generate.batch.WeatherObject.Builder clearWind() {
      wind = null;
      windBuilder = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    public WeatherObject build() {
      try {
        WeatherObject record = new WeatherObject();
        record.stationId = fieldSetFlags()[0] ? this.stationId : (java.lang.Integer) defaultValue(fields()[0]);
        if (geoLocationObjectBuilder != null) {
          record.geoLocationObject = this.geoLocationObjectBuilder.build();
        } else {
          record.geoLocationObject = fieldSetFlags()[1] ? this.geoLocationObject : (mteo.savand.avro_generate.batch.GeoLocationObject) defaultValue(fields()[1]);
        }
        record.date = fieldSetFlags()[2] ? this.date : (org.joda.time.DateTime) defaultValue(fields()[2]);
        record.temperatureInDegreesCelsious = fieldSetFlags()[3] ? this.temperatureInDegreesCelsious : (java.lang.Integer) defaultValue(fields()[3]);
        record.humidityInPercentage = fieldSetFlags()[4] ? this.humidityInPercentage : (java.lang.Integer) defaultValue(fields()[4]);
        if (windBuilder != null) {
          record.wind = this.windBuilder.build();
        } else {
          record.wind = fieldSetFlags()[5] ? this.wind : (mteo.savand.avro_generate.batch.WindObject) defaultValue(fields()[5]);
        }
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
