/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mteo.savand.avro_generate.batch;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum WindDirection {
  N, NNE, NE, ENE, E, ESE, SE, SSE, S, SSW, SW, WSW, W, WNW, NW, NNW  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"WindDirection\",\"namespace\":\"mteo.savand.avro_generate.batch\",\"symbols\":[\"N\",\"NNE\",\"NE\",\"ENE\",\"E\",\"ESE\",\"SE\",\"SSE\",\"S\",\"SSW\",\"SW\",\"WSW\",\"W\",\"WNW\",\"NW\",\"NNW\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
